components_manager:
    task_processors:                 

        main-task-processor:         
            worker_threads: $worker-threads        

        fs-task-processor:            
            worker_threads: $worker-fs-threads

    default_task_processor: main-task-processor

    components:                    
        server:
            listener:                
                port: $server-port       
                task_processor: main-task-processor   
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $logger-level
                    overflow_behavior: discard  

        dynamic-config:                     
            defaults:
                HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000

        testsuite-support: {}


        tests-control:
            load-enabled: $is_testing
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor


        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        http-client:
            load-enabled: $is_testing
            fs-task-processor: fs-task-processor

        dns-client:
            fs-task-processor: fs-task-processor
            

        handler-auth-register:
            path: /auth/register 
            method: POST             
            task_processor: main-task-processor

        handler-auth-login:
            path: /auth/login 
            method: POST             
            task_processor: main-task-processor

        chess_db:
            dbconnection: $dbconnection
            blocking_task_processor: fs-task-processor
            sync-start: true
