services:
  auth-service:
    privileged: true
    build:
      context: ..       
      dockerfile: ./.devcontainer/Dockerfile
      args:
        SERVICE_NAME: auth  
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - postgres
    volumes:
    - ../auth-service:/app/auth-service:rw
    - ../Makefile:/app/Makefile:rw
    - ../third_party:/app/third_party:rw
    - ../postgresql:/app/postgresql:rw

  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: chess_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ../postgresql/schemas:/docker-entrypoint-initdb.d
      - ../.pgdata:/var/lib/postgresql/data
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
